/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_Read_Door_State_.c
 * Generated on: Sun Oct 22 16:43:23 EEST
 ********************************************************************/

#include "string.h"
#include "Rte_Read_Door_State.h"


Rte_DE_myuint8 Read_Door_State_RP_DOOR_State_Sensor_Reading;
Rte_DE_myuint8 Read_Door_State_PP_DOOR_State_Door_State;


const Rte_CDS_Read_Door_State Rte_Instance_Read_Door_State = {
&Read_Door_State_RP_DOOR_State_Sensor_Reading,
&Read_Door_State_PP_DOOR_State_Door_State
};

const Rte_CDS_Read_Door_State * const Rte_Inst_Read_Door_State = &Rte_Instance_Read_Door_State;




void Rte_IWrite_Read_Door_State_Read_Door_State_PP_DOOR_State_Door_State (myuint8 Door_State)
{
	(Rte_Inst_Read_Door_State)->Read_Door_State_PP_DOOR_State_Door_State->value = Door_State;
}
myuint8* Rte_IWriteRef_Read_Door_State_Read_Door_State_PP_DOOR_State_Door_State(void)
{
	return &(Rte_Inst_Read_Door_State)->Read_Door_State_PP_DOOR_State_Door_State->value;
}
myuint8 Rte_IRead_Read_Door_State_Read_Door_State_RP_DOOR_State_Sensor_Reading (void)
{
	return (Rte_Inst_Read_Door_State)->Read_Door_State_RP_DOOR_State_Sensor_Reading->value;
}
