/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_ECU_Abstraction_SWC.h
 * Generated on: Sun Oct 22 16:43:23 EEST
 ********************************************************************/

#ifndef RTE_ECU_ABSTRACTION_SWC_H
#define RTE_ECU_ABSTRACTION_SWC_H

#include "Rte_ECU_Abstraction_SWC_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/**************** component data structure definition ****************/

#ifndef IN_RTE_C
typedef const Rte_CDS_ECU_Abstraction_SWC * const Rte_Instance;
#endif

/************************* instance handle ***************************/

extern const Rte_CDS_ECU_Abstraction_SWC * const Rte_Inst_ECU_Abstraction_SWC;

/************************ application errors *************************/

#define RTE_E_CS_Interface_E_OK ((Std_ReturnType)0)
#define RTE_E_CS_Interface_E_NOT_OK ((Std_ReturnType)1)

/*************************** init values *****************************/


/****************** per instance memory definition *******************/


/************************* exclusive areas ***************************/


/************************* RTE API mapping ***************************/

/*****************************************************
 * Port: 		PP_SR_DOOR_State
 * Interface:	SR_Interface_Door_Sensor
 * DataElement:	Sensor_Reading
 * Runnable:	Read_Door_Sensor
 *****************************************************/
extern void Rte_IWrite_ECU_Abstraction_SWC_Read_Door_Sensor_PP_SR_DOOR_State_Sensor_Reading (myuint8 Sensor_Reading);
#ifndef IN_RTE_C
#define Rte_IWrite_Read_Door_Sensor_PP_SR_DOOR_State_Sensor_Reading(RTEData) \
	Rte_IWrite_ECU_Abstraction_SWC_Read_Door_Sensor_PP_SR_DOOR_State_Sensor_Reading(RTEData)
#endif
extern myuint8* Rte_IWriteRef_ECU_Abstraction_SWC_Read_Door_Sensor_PP_SR_DOOR_State_Sensor_Reading(void);
#ifndef IN_RTE_C
#define Rte_IWriteRef_Read_Door_Sensor_PP_SR_DOOR_State_Sensor_Reading() \
	Rte_IWriteRef_ECU_Abstraction_SWC_Read_Door_Sensor_PP_SR_DOOR_State_Sensor_Reading()
#endif

/*****************************************************
 * Port: 		PP_CS_LED_Switch
 * Interface:	CS_Interface
 * Operation:	LED_Switch
 *****************************************************/
extern Std_ReturnType Switch_LED_State_Runnable(myuint8 LED_State) ;


/**************** event triggered runnable entities *******************/

/*****************************************************
 * Runnable: 	Read_Door_Sensor
 * Period:		0.01
 *****************************************************/
extern void Read_Door_Sensor_Runnable(void);


/******** ARUnit-specific function pointers for server call delegates *********/


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_ECU_ABSTRACTION_SWC_H */
