/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_Read_Door_State_Type.h
 * Generated on: Sun Oct 22 16:43:23 EEST
 ********************************************************************/

#ifndef RTE_READ_DOOR_STATE_TYPE_H
#define RTE_READ_DOOR_STATE_TYPE_H


#include "Rte_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/*************************** range types *****************************/

#define myuint8_LowerLimit  (0U)
#define myuint8_UpperLimit (255U)

/************************ enumeration types **************************/



#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_READ_DOOR_STATE_TYPE_H */
