/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_DoorLock_indication.h
 * Generated on: Sun Oct 22 16:43:23 EEST
 ********************************************************************/

#include "Rte_DoorLock_indication.h"	

#ifndef ARUNIT_DOORLOCK_INDICATION_H
#define ARUNIT_DOORLOCK_INDICATION_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef false
    #define false (0)
#endif
#ifndef true
    #define true  (!false)
#endif


void ARUnit_Initialize ();

/***************************************/
/******** Delegates API  ***************/
/***************************************/

/***************************************/
/******** Flags API  *******************/
/***************************************/

/***************************************/
/******** Implicit API  ****************/
/***************************************/
DECLSPEC_EXPORT void ARUnit_IWrite_DoorLock_indication_DoorLock_indication_PP_SR_LED_State_LED_State(myuint8 LED_State);
DECLSPEC_EXPORT myuint8 ARUnit_IRead_DoorLock_indication_DoorLock_indication_PP_SR_LED_State_LED_State(void);
DECLSPEC_EXPORT myuint8* ARUnit_IWriteRef_DoorLock_indication_DoorLock_indication_PP_SR_LED_State_LED_State(void);
DECLSPEC_EXPORT void ARUnit_IWrite_DoorLock_indication_DoorLock_indication_RP_SR_DOOR_State_Door_State(myuint8 Door_State);
DECLSPEC_EXPORT myuint8 ARUnit_IRead_DoorLock_indication_DoorLock_indication_RP_SR_DOOR_State_Door_State(void);
DECLSPEC_EXPORT myuint8* ARUnit_IWriteRef_DoorLock_indication_DoorLock_indication_RP_SR_DOOR_State_Door_State(void);
/***************************************/
/******** Explicit API  ****************/
/***************************************/
/***************************************/
/******** Runnable Calls****************/
/***************************************/

DECLSPEC_EXPORT void ARUnit_Trigger_DoorLock_indication_IB_DoorLock_indication_Runnable(void);

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* ARUNIT_DOORLOCK_INDICATION_H */
