/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_DoorLock_indication_.c
 * Generated on: Sun Oct 22 16:43:23 EEST
 ********************************************************************/

#include "string.h"
#include "ARUnit_DoorLock_indication.h"


extern const Rte_CDS_DoorLock_indication Rte_Instance_DoorLock_indication;
extern const Rte_CDS_DoorLock_indication * const Rte_Inst_DoorLock_indication;




DECLSPEC_EXPORT void ARUnit_IWrite_DoorLock_indication_DoorLock_indication_PP_SR_LED_State_LED_State(myuint8 LED_State)
{
		(Rte_Inst_DoorLock_indication)->DoorLock_indication_PP_SR_LED_State_LED_State->value = LED_State;
}
DECLSPEC_EXPORT myuint8* ARUnit_IWriteRef_DoorLock_indication_DoorLock_indication_PP_SR_LED_State_LED_State(void)
{
	return &(Rte_Inst_DoorLock_indication)->DoorLock_indication_PP_SR_LED_State_LED_State->value;
}
DECLSPEC_EXPORT myuint8 ARUnit_IRead_DoorLock_indication_DoorLock_indication_PP_SR_LED_State_LED_State(void)
{
	return (Rte_Inst_DoorLock_indication)->DoorLock_indication_PP_SR_LED_State_LED_State->value;
}
DECLSPEC_EXPORT void ARUnit_IWrite_DoorLock_indication_DoorLock_indication_RP_SR_DOOR_State_Door_State(myuint8 Door_State)
{
	(Rte_Inst_DoorLock_indication)->DoorLock_indication_RP_SR_DOOR_State_Door_State->value = Door_State;
}
DECLSPEC_EXPORT myuint8* ARUnit_IWriteRef_DoorLock_indication_DoorLock_indication_RP_SR_DOOR_State_Door_State(void)
{
	return &(Rte_Inst_DoorLock_indication)->DoorLock_indication_RP_SR_DOOR_State_Door_State->value;
}
DECLSPEC_EXPORT myuint8 ARUnit_IRead_DoorLock_indication_DoorLock_indication_RP_SR_DOOR_State_Door_State(void)
{
	return (Rte_Inst_DoorLock_indication)->DoorLock_indication_RP_SR_DOOR_State_Door_State->value;
}


DECLSPEC_EXPORT void ARUnit_Trigger_DoorLock_indication_IB_DoorLock_indication_Runnable(void)
{
	IB_DoorLock_indication_Runnable();
}
