/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_ECU_Abstraction_SWC_.c
 * Generated on: Sun Oct 22 16:43:23 EEST
 ********************************************************************/

#include "string.h"
#include "ARUnit_ECU_Abstraction_SWC.h"


extern const Rte_CDS_ECU_Abstraction_SWC Rte_Instance_ECU_Abstraction_SWC;
extern const Rte_CDS_ECU_Abstraction_SWC * const Rte_Inst_ECU_Abstraction_SWC;




DECLSPEC_EXPORT void ARUnit_IWrite_ECU_Abstraction_SWC_Read_Door_Sensor_PP_SR_DOOR_State_Sensor_Reading(myuint8 Sensor_Reading)
{
		(Rte_Inst_ECU_Abstraction_SWC)->Read_Door_Sensor_PP_SR_DOOR_State_Sensor_Reading->value = Sensor_Reading;
}
DECLSPEC_EXPORT myuint8* ARUnit_IWriteRef_ECU_Abstraction_SWC_Read_Door_Sensor_PP_SR_DOOR_State_Sensor_Reading(void)
{
	return &(Rte_Inst_ECU_Abstraction_SWC)->Read_Door_Sensor_PP_SR_DOOR_State_Sensor_Reading->value;
}
DECLSPEC_EXPORT myuint8 ARUnit_IRead_ECU_Abstraction_SWC_Read_Door_Sensor_PP_SR_DOOR_State_Sensor_Reading(void)
{
	return (Rte_Inst_ECU_Abstraction_SWC)->Read_Door_Sensor_PP_SR_DOOR_State_Sensor_Reading->value;
}
DECLSPEC_EXPORT Std_ReturnType ARUnit_Trigger_ECU_Abstraction_SWC_Switch_LED_State_Runnable(myuint8 LED_State)
{
	return Switch_LED_State_Runnable(LED_State);
}


DECLSPEC_EXPORT void ARUnit_Trigger_ECU_Abstraction_SWC_Read_Door_Sensor_Runnable(void)
{
	Read_Door_Sensor_Runnable();
}
