/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_LED_Actuator_.c
 * Generated on: Sun Oct 22 16:43:23 EEST
 ********************************************************************/

#include "string.h"
#include "ARUnit_LED_Actuator.h"


extern const Rte_CDS_LED_Actuator Rte_Instance_LED_Actuator;
extern const Rte_CDS_LED_Actuator * const Rte_Inst_LED_Actuator;


extern Std_ReturnType LED_Actuator_RP_CS_LED_Switch_LED_Switch_Buffer_retcode;

extern FunctionPtr_LED_Actuator_RP_CS_LED_Switch_LED_Switch Rte_Call_LED_Actuator_RP_CS_LED_Switch_LED_Switch_Delegate;

DECLSPEC_EXPORT void ARUnit_IWrite_LED_Actuator_Read_LED_State_RP_SR_LED_State_LED_State(myuint8 LED_State)
{
	(Rte_Inst_LED_Actuator)->Read_LED_State_RP_SR_LED_State_LED_State->value = LED_State;
}
DECLSPEC_EXPORT myuint8* ARUnit_IWriteRef_LED_Actuator_Read_LED_State_RP_SR_LED_State_LED_State(void)
{
	return &(Rte_Inst_LED_Actuator)->Read_LED_State_RP_SR_LED_State_LED_State->value;
}
DECLSPEC_EXPORT myuint8 ARUnit_IRead_LED_Actuator_Read_LED_State_RP_SR_LED_State_LED_State(void)
{
	return (Rte_Inst_LED_Actuator)->Read_LED_State_RP_SR_LED_State_LED_State->value;
}
DECLSPEC_EXPORT void ARUnit_Call_LED_Actuator_RP_CS_LED_Switch_LED_Switch_ReturnCode(Std_ReturnType returnCode)
{
	LED_Actuator_RP_CS_LED_Switch_LED_Switch_Buffer_retcode = returnCode;
}

DECLSPEC_EXPORT void ARUnit_Set_LED_Actuator_RP_CS_LED_Switch_LED_Switch_Delegate(FunctionPtr_LED_Actuator_RP_CS_LED_Switch_LED_Switch  delegate)
{
	Rte_Call_LED_Actuator_RP_CS_LED_Switch_LED_Switch_Delegate = delegate;
}

DECLSPEC_EXPORT void ARUnit_Trigger_LED_Actuator_Read_LED_State_Runnable(void)
{
	Read_LED_State_Runnable();
}
