/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_Read_Door_State.h
 * Generated on: Sun Oct 22 16:43:23 EEST
 ********************************************************************/

#include "Rte_Read_Door_State.h"	

#ifndef ARUNIT_READ_DOOR_STATE_H
#define ARUNIT_READ_DOOR_STATE_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef false
    #define false (0)
#endif
#ifndef true
    #define true  (!false)
#endif


void ARUnit_Initialize ();

/***************************************/
/******** Delegates API  ***************/
/***************************************/

/***************************************/
/******** Flags API  *******************/
/***************************************/

/***************************************/
/******** Implicit API  ****************/
/***************************************/
DECLSPEC_EXPORT void ARUnit_IWrite_Read_Door_State_Read_Door_State_PP_DOOR_State_Door_State(myuint8 Door_State);
DECLSPEC_EXPORT myuint8 ARUnit_IRead_Read_Door_State_Read_Door_State_PP_DOOR_State_Door_State(void);
DECLSPEC_EXPORT myuint8* ARUnit_IWriteRef_Read_Door_State_Read_Door_State_PP_DOOR_State_Door_State(void);
DECLSPEC_EXPORT void ARUnit_IWrite_Read_Door_State_Read_Door_State_RP_DOOR_State_Sensor_Reading(myuint8 Sensor_Reading);
DECLSPEC_EXPORT myuint8 ARUnit_IRead_Read_Door_State_Read_Door_State_RP_DOOR_State_Sensor_Reading(void);
DECLSPEC_EXPORT myuint8* ARUnit_IWriteRef_Read_Door_State_Read_Door_State_RP_DOOR_State_Sensor_Reading(void);
/***************************************/
/******** Explicit API  ****************/
/***************************************/
/***************************************/
/******** Runnable Calls****************/
/***************************************/

DECLSPEC_EXPORT void ARUnit_Trigger_Read_Door_State_Read_Door_State_Runnable(void);

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* ARUNIT_READ_DOOR_STATE_H */
