/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_Read_Door_State_.c
 * Generated on: Sun Oct 22 16:43:23 EEST
 ********************************************************************/

#include "string.h"
#include "ARUnit_Read_Door_State.h"


extern const Rte_CDS_Read_Door_State Rte_Instance_Read_Door_State;
extern const Rte_CDS_Read_Door_State * const Rte_Inst_Read_Door_State;




DECLSPEC_EXPORT void ARUnit_IWrite_Read_Door_State_Read_Door_State_PP_DOOR_State_Door_State(myuint8 Door_State)
{
		(Rte_Inst_Read_Door_State)->Read_Door_State_PP_DOOR_State_Door_State->value = Door_State;
}
DECLSPEC_EXPORT myuint8* ARUnit_IWriteRef_Read_Door_State_Read_Door_State_PP_DOOR_State_Door_State(void)
{
	return &(Rte_Inst_Read_Door_State)->Read_Door_State_PP_DOOR_State_Door_State->value;
}
DECLSPEC_EXPORT myuint8 ARUnit_IRead_Read_Door_State_Read_Door_State_PP_DOOR_State_Door_State(void)
{
	return (Rte_Inst_Read_Door_State)->Read_Door_State_PP_DOOR_State_Door_State->value;
}
DECLSPEC_EXPORT void ARUnit_IWrite_Read_Door_State_Read_Door_State_RP_DOOR_State_Sensor_Reading(myuint8 Sensor_Reading)
{
	(Rte_Inst_Read_Door_State)->Read_Door_State_RP_DOOR_State_Sensor_Reading->value = Sensor_Reading;
}
DECLSPEC_EXPORT myuint8* ARUnit_IWriteRef_Read_Door_State_Read_Door_State_RP_DOOR_State_Sensor_Reading(void)
{
	return &(Rte_Inst_Read_Door_State)->Read_Door_State_RP_DOOR_State_Sensor_Reading->value;
}
DECLSPEC_EXPORT myuint8 ARUnit_IRead_Read_Door_State_Read_Door_State_RP_DOOR_State_Sensor_Reading(void)
{
	return (Rte_Inst_Read_Door_State)->Read_Door_State_RP_DOOR_State_Sensor_Reading->value;
}


DECLSPEC_EXPORT void ARUnit_Trigger_Read_Door_State_Read_Door_State_Runnable(void)
{
	Read_Door_State_Runnable();
}
