/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_LED_Actuator.h
 * Generated on: Sun Oct 22 16:43:23 EEST
 ********************************************************************/

#include "Rte_LED_Actuator.h"	

#ifndef ARUNIT_LED_ACTUATOR_H
#define ARUNIT_LED_ACTUATOR_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef false
    #define false (0)
#endif
#ifndef true
    #define true  (!false)
#endif


void ARUnit_Initialize ();

/***************************************/
/******** Delegates API  ***************/
/***************************************/
DECLSPEC_EXPORT void ARUnit_Set_LED_Actuator_RP_CS_LED_Switch_LED_Switch_Delegate(FunctionPtr_LED_Actuator_RP_CS_LED_Switch_LED_Switch );
DECLSPEC_EXPORT void ARUnit_Call_LED_Actuator_RP_CS_LED_Switch_LED_Switch_ReturnCode(Std_ReturnType returnCode);

/***************************************/
/******** Flags API  *******************/
/***************************************/

/***************************************/
/******** Implicit API  ****************/
/***************************************/
DECLSPEC_EXPORT void ARUnit_IWrite_LED_Actuator_Read_LED_State_RP_SR_LED_State_LED_State(myuint8 LED_State);
DECLSPEC_EXPORT myuint8 ARUnit_IRead_LED_Actuator_Read_LED_State_RP_SR_LED_State_LED_State(void);
DECLSPEC_EXPORT myuint8* ARUnit_IWriteRef_LED_Actuator_Read_LED_State_RP_SR_LED_State_LED_State(void);
/***************************************/
/******** Explicit API  ****************/
/***************************************/
/***************************************/
/******** Runnable Calls****************/
/***************************************/

DECLSPEC_EXPORT void ARUnit_Trigger_LED_Actuator_Read_LED_State_Runnable(void);

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* ARUNIT_LED_ACTUATOR_H */
