/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_DoorLock_indication.h
 * Generated on: Sun Oct 22 16:43:23 EEST
 ********************************************************************/

#ifndef RTE_DOORLOCK_INDICATION_H
#define RTE_DOORLOCK_INDICATION_H

#include "Rte_DoorLock_indication_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/**************** component data structure definition ****************/

#ifndef IN_RTE_C
typedef const Rte_CDS_DoorLock_indication * const Rte_Instance;
#endif

/************************* instance handle ***************************/

extern const Rte_CDS_DoorLock_indication * const Rte_Inst_DoorLock_indication;

/************************ application errors *************************/


/*************************** init values *****************************/


/****************** per instance memory definition *******************/


/************************* exclusive areas ***************************/


/************************* RTE API mapping ***************************/

/*****************************************************
 * Port: 		PP_SR_LED_State
 * Interface:	SR_Interface_LED_State
 * DataElement:	LED_State
 * Runnable:	DoorLock_indication
 *****************************************************/
extern void Rte_IWrite_DoorLock_indication_DoorLock_indication_PP_SR_LED_State_LED_State (myuint8 LED_State);
#ifndef IN_RTE_C
#define Rte_IWrite_DoorLock_indication_PP_SR_LED_State_LED_State(RTEData) \
	Rte_IWrite_DoorLock_indication_DoorLock_indication_PP_SR_LED_State_LED_State(RTEData)
#endif
extern myuint8* Rte_IWriteRef_DoorLock_indication_DoorLock_indication_PP_SR_LED_State_LED_State(void);
#ifndef IN_RTE_C
#define Rte_IWriteRef_DoorLock_indication_PP_SR_LED_State_LED_State() \
	Rte_IWriteRef_DoorLock_indication_DoorLock_indication_PP_SR_LED_State_LED_State()
#endif

/*****************************************************
 * Port: 		RP_SR_DOOR_State
 * Interface:	SR_Interface_Door_State
 * DataElement:	Door_State
 * Runnable:	DoorLock_indication
 *****************************************************/
extern myuint8 Rte_IRead_DoorLock_indication_DoorLock_indication_RP_SR_DOOR_State_Door_State (void);
#ifndef IN_RTE_C
#define Rte_IRead_DoorLock_indication_RP_SR_DOOR_State_Door_State() \
	Rte_IRead_DoorLock_indication_DoorLock_indication_RP_SR_DOOR_State_Door_State()
#endif


/**************** event triggered runnable entities *******************/

/*****************************************************
 * Runnable: 	DoorLock_indication
 * Period:		0.015
 *****************************************************/
extern void IB_DoorLock_indication_Runnable(void);


/******** ARUnit-specific function pointers for server call delegates *********/


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_DOORLOCK_INDICATION_H */
