/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_LED_Actuator_.c
 * Generated on: Sun Oct 22 16:43:23 EEST
 ********************************************************************/

#include "string.h"
#include "Rte_LED_Actuator.h"

Rte_DE_myuint8 DoorLock_indication_PP_SR_LED_State_LED_State;
//Rte_DE_myuint8 Read_LED_State_RP_SR_LED_State_LED_State;


const Rte_CDS_LED_Actuator Rte_Instance_LED_Actuator = {
&DoorLock_indication_PP_SR_LED_State_LED_State
};

const Rte_CDS_LED_Actuator * const Rte_Inst_LED_Actuator = &Rte_Instance_LED_Actuator;


Std_ReturnType LED_Actuator_RP_CS_LED_Switch_LED_Switch_Buffer_retcode = RTE_E_OK;

FunctionPtr_LED_Actuator_RP_CS_LED_Switch_LED_Switch Rte_Call_LED_Actuator_RP_CS_LED_Switch_LED_Switch_Delegate = 0;

myuint8 Rte_IRead_LED_Actuator_Read_LED_State_RP_SR_LED_State_LED_State (void)
{
	return (Rte_Inst_LED_Actuator)->Read_LED_State_RP_SR_LED_State_LED_State->value;
}
Std_ReturnType Rte_Call_LED_Actuator_RP_CS_LED_Switch_LED_Switch (myuint8 LED_State)
{
	Std_ReturnType __result = LED_Actuator_RP_CS_LED_Switch_LED_Switch_Buffer_retcode;
	if ( Rte_Call_LED_Actuator_RP_CS_LED_Switch_LED_Switch_Delegate != 0 ) {
		__result = Rte_Call_LED_Actuator_RP_CS_LED_Switch_LED_Switch_Delegate(LED_State);
	}
	__result=Switch_LED_State_Runnable(LED_State);
	return __result;
}
