/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_Read_Door_State.h
 * Generated on: Sun Oct 22 16:43:23 EEST
 ********************************************************************/

#ifndef RTE_READ_DOOR_STATE_H
#define RTE_READ_DOOR_STATE_H

#include "Rte_Read_Door_State_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/**************** component data structure definition ****************/

#ifndef IN_RTE_C
typedef const Rte_CDS_Read_Door_State * const Rte_Instance;
#endif

/************************* instance handle ***************************/

extern const Rte_CDS_Read_Door_State * const Rte_Inst_Read_Door_State;

/************************ application errors *************************/


/*************************** init values *****************************/


/****************** per instance memory definition *******************/


/************************* exclusive areas ***************************/


/************************* RTE API mapping ***************************/

/*****************************************************
 * Port: 		PP_DOOR_State
 * Interface:	SR_Interface_Door_State
 * DataElement:	Door_State
 * Runnable:	Read_Door_State
 *****************************************************/
extern void Rte_IWrite_Read_Door_State_Read_Door_State_PP_DOOR_State_Door_State (myuint8 Door_State);
#ifndef IN_RTE_C
#define Rte_IWrite_Read_Door_State_PP_DOOR_State_Door_State(RTEData) \
	Rte_IWrite_Read_Door_State_Read_Door_State_PP_DOOR_State_Door_State(RTEData)
#endif
extern myuint8* Rte_IWriteRef_Read_Door_State_Read_Door_State_PP_DOOR_State_Door_State(void);
#ifndef IN_RTE_C
#define Rte_IWriteRef_Read_Door_State_PP_DOOR_State_Door_State() \
	Rte_IWriteRef_Read_Door_State_Read_Door_State_PP_DOOR_State_Door_State()
#endif

/*****************************************************
 * Port: 		RP_DOOR_State
 * Interface:	SR_Interface_Door_Sensor
 * DataElement:	Sensor_Reading
 * Runnable:	Read_Door_State
 *****************************************************/
extern myuint8 Rte_IRead_Read_Door_State_Read_Door_State_RP_DOOR_State_Sensor_Reading (void);
#ifndef IN_RTE_C
#define Rte_IRead_Read_Door_State_RP_DOOR_State_Sensor_Reading() \
	Rte_IRead_Read_Door_State_Read_Door_State_RP_DOOR_State_Sensor_Reading()
#endif


/**************** event triggered runnable entities *******************/

/*****************************************************
 * Runnable: 	Read_Door_State
 * Period:		0.012
 *****************************************************/
extern void Read_Door_State_Runnable(void);


/******** ARUnit-specific function pointers for server call delegates *********/


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_READ_DOOR_STATE_H */
