/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_LED_Actuator.h
 * Generated on: Sun Oct 22 16:43:23 EEST
 ********************************************************************/

#ifndef RTE_LED_ACTUATOR_H
#define RTE_LED_ACTUATOR_H

#include "Rte_LED_Actuator_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/**************** component data structure definition ****************/

#ifndef IN_RTE_C
typedef const Rte_CDS_LED_Actuator * const Rte_Instance;
#endif

/************************* instance handle ***************************/

extern const Rte_CDS_LED_Actuator * const Rte_Inst_LED_Actuator;

/************************ application errors *************************/

#define RTE_E_CS_Interface_E_OK ((Std_ReturnType)0)
#define RTE_E_CS_Interface_E_NOT_OK ((Std_ReturnType)1)

/*************************** init values *****************************/


/****************** per instance memory definition *******************/


/************************* exclusive areas ***************************/


/************************* RTE API mapping ***************************/

/*****************************************************
 * Port: 		RP_SR_LED_State
 * Interface:	SR_Interface_LED_State
 * DataElement:	LED_State
 * Runnable:	Read_LED_State
 *****************************************************/
extern myuint8 Rte_IRead_LED_Actuator_Read_LED_State_RP_SR_LED_State_LED_State (void);
#ifndef IN_RTE_C
#define Rte_IRead_Read_LED_State_RP_SR_LED_State_LED_State() \
	Rte_IRead_LED_Actuator_Read_LED_State_RP_SR_LED_State_LED_State()
#endif

/*****************************************************
 * Port: 		RP_CS_LED_Switch
 * Interface:	CS_Interface
 * Operation:	LED_Switch
 * Sync/Async:	Synchronous
 *****************************************************/
extern Std_ReturnType Rte_Call_LED_Actuator_RP_CS_LED_Switch_LED_Switch (myuint8 LED_State);
#ifndef IN_RTE_C
#define Rte_Call_RP_CS_LED_Switch_LED_Switch(LED_State) \
	Rte_Call_LED_Actuator_RP_CS_LED_Switch_LED_Switch(LED_State)
#endif


/**************** event triggered runnable entities *******************/

/*****************************************************
 * Runnable: 	Read_LED_State
 * Period:		0.018
 *****************************************************/
extern void Read_LED_State_Runnable(void);


/******** ARUnit-specific function pointers for server call delegates *********/
typedef Std_ReturnType (*FunctionPtr_LED_Actuator_RP_CS_LED_Switch_LED_Switch)(myuint8 LED_State);


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_LED_ACTUATOR_H */
